### ISSUE TITLE
Which SDK version is running?

### ISSUE THREAD

**Issue by steadysupply** [pebble-dev/rebble-docker#3]
After invoking `docker run --name=RebbleSDK -it rebble/pebble-sdk` I see
```
root@798da9776ea8:/opt/pebble-sdk-4.5-linux64# pebble sdk list
Installed SDKs:
4.3 (active)

Available SDKs:
Could not fetch list of available SDKs.
```
Am I on `4.3` or `4.5`!?

**Comment by AliceGrey** [comment]
Please see https://developer.rebble.io/developer.pebble.com/sdk/index.html. you are on pebble-tool version 4.5 which is sdk 4.3.
